#' Build the Model Specification Function
#'
#' Uses metaprogramming to construct the new model specification function
#' (e.g., `dynamic_mlp()`). This function will capture user-provided arguments
#' and package them into a `parsnip::new_model_spec()` call.
#'
#' @param model_name The name of the model specification function to create.
#' @param mode The model mode ("regression" or "classification").
#' @param all_args A named list of arguments for the function signature, as
#'   generated by `collect_spec_args()`.
#' @param parsnip_names A character vector of all argument names.
#' @return A new function that serves as the `parsnip` model specification.
#' @noRd
build_spec_function <- function(
  model_name,
  mode,
  all_args,
  parsnip_names,
  layer_blocks
) {
  quos_exprs <- purrr::map(
    parsnip_names,
    ~ rlang::expr(rlang::enquo(!!rlang::sym(.x)))
  )
  names(quos_exprs) <- parsnip_names

  body <- rlang::expr({
    # Capture both explicit args and ... to pass to the fit impl
    # Named arguments are captured into a list of quosures.
    main_args <- rlang::list2(!!!quos_exprs)
    # ... arguments are captured into a separate list of quosures.
    dot_args <- rlang::enquos(...)
    args <- c(main_args, dot_args)
    parsnip::new_model_spec(
      !!model_name,
      args = args,
      eng_args = NULL,
      mode = !!mode,
      method = NULL,
      engine = NULL
    )
  })

  # Add ... to the function signature to capture any other compile arguments
  fn_args <- c(all_args, list(... = rlang::missing_arg()))

  fn <- rlang::new_function(args = fn_args, body = body)

  docs <- generate_roxygen_docs(model_name, layer_blocks, all_args)
  comment(fn) <- docs
  fn
}